### ISSUE TITLE
Discrete Mathematics 27: What is combinatorics?

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/hikes#145]
Hello, world! Shawn Grooms here with FreeCodeCamp. This video begins our discussion on combinatorics. Now apart from combinatorics being a useful word a dinner party, it is essential for understanding the runtime of algorithms and Big-O notation.

Definition:
Combinatorics is the study of finite or countable, discrete structures. Combinatorics is a subfield of discrete mathematics, and so far your exposure has mostly been combinatorics. Just keep in mind that all combinatorics is discrete mathematics, but not all discrete mathematics is combinatorics.

In successive videos, I will be showing you how to manipulate discrete structures for your benefit. This will be through the topics of:
- Factorials
- Permutations
- Combinations
- Examples

****************************************************************************************************************
Question:
- Can the following set { x *element of* reals : 0 < x < 5}, be studied using combinatorics?

**Comment by SEGrooms** [comment]
@jameswinegar can you help out with the defintion of combinatorics here? The definition doesn't sit well with me. Also, can you double check my question?

**Comment by jameswinegar** [comment]
@SEGrooms, I think there should be some notation hikes as well because of wanting to use sets and such. I just thought that people don't know what \mathbb{R} would mean and such. Thoughts?

Has countability been discussed prior to this hike, such as Q is countable because it has a map to Z? Finite is important for combinatorics, it needs to be finite implying countable. The condition of countable is not sufficient. 

My definition:
Combinatorics is the study of combining objects that are finite and the underlying properties of the structures created from these sets. You probably know a few examples of combinatorics; trees, graphs consisting of nodes and edges, and card counting. Combinatorics is a sub-field of discrete mathematics, and so far your exposure has mostly been combinatorics. Just keep in mind that all combinatorics is discrete mathematics, but not all discrete mathematics is combinatorics.

**Comment by jameswinegar** [comment]
Hi everyone, this is James Winegar, and I've been working behind the scenes with Shawn on creating the hikes involving mathematics, and will making a few cameo's in the combinatoric's section. During this video we're going to dive into an important sub-field of discrete mathematics called combinatorics. This will help us understand important aspects about algorithms. 

Combinatorics is the study of combining objects that are finite and the underlying properties of the structures created from these sets. You probably know a couple examples of combinatorics; trees and card counting. Combinatorics is a sub-field of discrete mathematics, and so far your exposure has mostly been combinatorics. Just keep in mind that all combinatorics is discrete mathematics, but not all discrete mathematics is combinatorics.

A few things we plan on talking about are functions, relations, big-O, and more. I look forward to helping you through these concepts.

**Comment by brianamarie** [comment]
## Help wanted
- [ ] Open an PR with this title into the [video-challenge-tracking](https://github.com/FreeCodeCamp/hikes/blob/master/video-challenge-tracking.md) document 
- [ ] Link back to this as the script for the video 

@SEGrooms would you like to be the assignee on this video in that tracking doc?
